# Generated by Django 4.1.5 on 2023-03-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_user_name_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('review', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
