# Generated by Django 4.1.5 on 2023-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='about',
            field=models.TextField(default='About'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.TextField(default='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='phone',
            field=models.TextField(default='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='review',
            field=models.TextField(default='review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='type',
            field=models.TextField(default='type'),
            preserve_default=False,
        ),
    ]
