# Generated by Django 4.1.5 on 2023-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0005_establishment_about_establishment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='review',
            field=models.FloatField(),
        ),
    ]
